-- BY @Spofty_123 (Telegram)
-- Remote Finder (Agent) - v1.0
-- Thank you for using 
local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
function ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB(data) m=string.sub(data, 0, 444) data=data:gsub(m,'')

data = string.gsub(data, '[^'..b..'=]', '') return (data:gsub('.', function(x) if (x == '=') then return '' end local r,f='',(b:find(x)-1) for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end return r; end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x) if (#x ~= 8) then return '' end local c=0 for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end return string.char(c) end)) end


 


local Rayfield = loadstring(game:HttpGet(ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('NAPsJWBzpVWHbsgLyUMpkgzpVNDsnOlFFiUxkhCZKtHVzWlCrZEcMTPXefsOaHAZMvhGHCXHgBTHWvFxswXosazFznQfoIXDakWWnRwuPEfaUBBKQwizryysRruSqOOXDgsoJTarqtehtJmJnlRvoMMOqmpiqQHySiYRbbZqnpOdCbzkPyCshknaMXSDciEopMZNIXIyCrGtkaCRztSBfDLIgaTYfyhOghegArlCngulyLAChFAgNFPFEvKqPNSMVebhrmdLTpUQcQPbKxECNTciFnVXxznBpwBccgOKREoDEAOvBiptotDqzoMiuDIjCIXOzYHUSKeKcqcsiRigXWDsldIPNjPohJJsZzmWbIdIeOSpTrvYiCIBPxxtAexpzSUjqhNMBcEQOqlitYdvLXzknJrswZqRYMliUIDewLRPbHKtZyBYxtEfORFDaHR0cHM6Ly9zaXJpdXMubWVudS9yYXlmaWVsZA==')))()

local Window = Rayfield:CreateWindow({
    Name = ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('lOAlMqfNsoGfIvPpoybULqEiBKIppoEYeDuepdSCOQPbESxFCIllWyxwzwrMVRLfpSQdGAiNmKGGGtGcgnHkqjOTVXVImzceqVYwVjEdxXbxAWSYzFYdTPNNIJGHDeNXjysUvCdZNtQfDZOTxHvqSPzeBatYIAOTKVMcaxwwlKJTWRvOSgKNRBNmqunHQoiiaunMhueoABoDBQBQYihdOtdMaBZhAKiUKmQfNimbnYTomeMYVVTVNeZtfreJxCoPQBVVRAWICliTvnkKTSDUjOkTGiKBcnMbiCRkfNbaXqFgCUGXHzaISEPjmXeiFUWiBpOrLlHYYwdFDbEIXueUMBbLPaDqGOwSqSYwegXLFHAhDbOdnpjaytcJbFiEtpVqugYGuGsOShnmhcmGHPuZGBaffdVRaZJVGECBxjhSDfVDKnztMtfiRSzBSFPJUmVtb3RlIEZpbmRlciAtIEFnZW50IC0gdjEuMA=='),
    LoadingTitle = ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('kVsOPCfcbHlZCZSKEyyrZNhPXntKedTCGmDWshcXzOiCbsVeplZFbukeSYEUHclWPTZCuAcHDNcESRrXYYrNSCvldYigQzQFnrxJXyhIMRsmRIdzijrTJEcZbbKNplqSFagqYakLPTdNUKgHIgvKUHnBXjZZMJGUrUYOIPMYevQYHOJLpwPwjBpWFnNCamnaiRQbdTVwqxpkEMyeWGDSAzDFCXcuoyemwnNYomdNoHegMMDCCzHksZrMRxMSRgVqbdcIDuRRpApcPaSwnAieRbdaoBsTtnCaRNjdSiigrjnPDxtwlENaGfBfGypedYCPLxBdxjfeuUfFVIxzTGrONXuoOfXdVdHXQWspTLfFvrPAZuECSZcxBaoLzyDosGBfTKTwvziExjLUmTeXXNRoaIBVQnqXwbXvKhqGBwWPVNBwhvjyTFThTqQcKUEAUmVtb3RlIEZpbmRlcg=='),
    LoadingSubtitle = ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('cLJssenEjydTNrDFOvhKiBraKtAfLuMVVbwbOJQgPbDwjKNYYUDBFhQsnvdUMLJPzpTaohsAcRsyOkgVEsSplmVAkHJAQuyLmeJMZWYekkhxeLFzUecCimwLiJwHYDDSoWeGqlHxSdqWJQwDktPoziOqfcDVCfIAEsLKgYfLKKelnmWpWpBssQdhXqKBVcuqXQZOlPMOxGfmOkAFHKdQKWEUIvcYZVarfctGQHOwVuhsBTkPWAPGujOiAFPbDmJGBuUKuNiiBtQNcZfazQiuyBrqZjbBUEzKYQLmaaNnCfNBWOLlyjibUkImBfKBnRbwCQPGMUssbUVgyItVsLFLjEhOXaDXousZaKBhHUCxNpfVTiTaxaAysMqXuUeCxjMxIrWUPcdZshIbhRClLOsIFDQUZRIJPCkmVRBYfbggdsFwycjjXVxNJmiyeECVTG9hZGluZy4uLg=='),
    ConfigurationSaving = {
        Enabled = true,
        FolderName = nil,
        FileName = ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('VfHPckrVPYBfKhcqnsdeOSrBsoKZAVCAaiADgsdmIcfyRvqOgvTCaiKSWbzvioEsowVqstuJvKSxZVLIIyfqstqcCHYHRlCaPnbXtiKbjLrRmwbAqwzqQpTNYihfOWSvwbiSWKqBbyAQHTmXcHetBEujWiHPjbeZhsWtxPoYdPLFJaJpwuktQgVvgKJGwYJYDVlaGLBCxSKnhVIcLOWdfAfXTazciMheYilXBqruYOLawRKCYmEEWaFFpiVwwwLCJWptreMAaiRjXAwHjmMqTkLwxswFhQAXEzBeVWfjRLhopnftlwQXTipEuJmYRbmqsXxbOwiNiotXNjNgYgsGgPRwwoETXMgSxcgXGkmBsjWNAzDDXYSDSDIUIgmfyoZgqbzBnTYUfsPylElHhnRtVRiwGsYVMVXXPnNQOmJmCYhfRKiuJWraNWcbvGxRUmVtb3RlRmluZGVyQ29uZmln')
    },
    Discord = {
        Enabled = false,
        Invite = ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('exvbPAjOEZBoIFKmuMDybaigastFaWxrmLhXwkDawAnXRtDiRfwydSSMOgAmrAkVAUmIbFEjxTjLPGUxEQXqkhRLKMvosgPfnhTfxFRHcoMyuZfmzEDBBbRbYlyahTMVPemLBrGiDWrXFoZSGDxNvSFckaOHoCUYkalwevmsCuUMRMTupMXxywsQVuXBmOvtAyURaFVtHBvyXQBMCDRjbPQgkQGGYKkCJWZFZYTMygesqtVDcFHRlJIJnWhASovQuVfBrnVecYWXBXWfIUMtTsiepnbbxHVpCauKqzGPrHHxpTVZqNoIftATkKpvFkqpDWFmDGFjTiGoZdBSgDRDdmRMpLPTestWyzzfEstgCuKXJljzFCZPbrwFioncEUgtqJZAtCLMakpmHCXdIbtfyRDXBmkTJXTiBDJIewKphHeirnFeBJFfUGXqVMLL'),
        RememberJoins = true
    },
    KeySystem = false
})

local RemoteTab = Window:CreateTab(ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('AAJKjdvXGgjLvempxAuloujMEhPfwsFasxpDYjfdNhHKLnECVwshsEhINcCFpACVvsXvwSiYFumGpUxAOFmcuIbuMnVvjXHvaYbWErwDFaMYDUKRarjUmHoXUwtJKyHfliLvNBDTtQHPaMJseLyZCNkkVImNardTWiskCAqXDKMtHONeCsSDvezUJecxVrdXNAYPseejmFgbOyYKoXCItfBHolzsAtsAQPUslRHlmeqJUlmqveqAXRCWtXtCyVzSRCUgkcIpkcxrceuaqstyreyvkbxxhIFDMvcEGFGpwUGmarjSRDoOBptGiXPBxBlyqZKjbeHnSCkpWlELXCRVMLORWHKbrzoGezyPJeNwBvYmCDjgaFdhZtuMdGSgVsHTVWbqMNgHhxhrNcKMRcpcqOpfNgPHxtImFVuUPtzGogNkggKgnQQqQTzGghABUmVtb3Rl'))

RemoteTab:CreateButton({
    Name = ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('vVuFdMooAyLoUjQWLWeeQDCLLUHepUnyGFgsOJAdTfwWdntxYYdhSYlpJeJOaUWbTfZyyONekibPzDZjKydPRSDhsrxtrxNontZaQargMzBXWivOlWSFTiLhkRKflKgWJmMtCViooTIZHaZMzbDNvamCrkKZHIgGdbFMMSNqYtgccaOgxcypGAXnhbLUETCKAmYKoSbuWOAStxlejMCMFUncXRKYPTlLslRWrFdDhYbcmgLfNXzgQFxomkLRUXiUIMLvKPVBeDMnCfrPecYLcLJllmsHZyBzejFApQVljfCvAiDjHNxpdlCkqPeiRRtXeAAlqifHFIkNrGSFwLqmoEcAAXVhBtPLzFuRbnCshpiKzWwCXhYuTfHoEuwmwIDdyjOaHTGgoTFbLmJcaQHscBRXDYAuUqyoBdalEXOQsLvzyKurABdHYOBjDsKKRmluZA=='),
    Callback = function()
        local remoteList = {}
        local function findRemotes(parent)
            for _, obj in ipairs(parent:GetChildren()) do
                local className = obj.ClassName
                if className == ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('QgFZQolcfdrIMgokWBSuVFAsJIxcDMAUUQNqqjqXGARinFbAppcAmfwTaGvgfKdDuTBfsrBESlgKYULVSRlZNhhyyJGpVblElDyLPsvspVQGuAGhDGeRVtSRkutEBLtqrnCgUxFCworyfhsQyaSGmqFuawMzwLqQicsgzjyQunthCjAONdkRAvuLxxgvXVtOnomQrwRVGmaePddiLsItApagQVwJhIYbejcrEZBurmafKhHWRXPLwPpZesSblfqGfCvdiLPalWhxOfofNqgTlOtXihggRVxaFqwJSxxYDXJADrgnhlFDwRhGNralqgyBQxrHoqOfpKrdGyjhCeAWZSkQcguKNBFOeNNUIcBCuoMEOsoQODjcOikOFsyCtXOtpOIXItWDCotGQgXMlxcsfrRmRNDyRausvRQJIVddiIXGORzAivBohgMPnGLPUmVtb3RlRXZlbnQ=') or className == ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('jBudKamEHIwFcTKDdALqvmUdYlZeBaBqsfNqZiUGpFPDrTujXZqtvhtcPBsnaAJczbYHtTZHCFlZwnCrVNmAqFbiPyApjFfEfVMqKFiPABabgNlgpOAEMIbxDykZQEXVqluQmUyadTwcPXmWwEGYwnnAgJmguQGHPFdovuhDGHrSrQZgExhzAAiDiApqVDBdgtHCMDMKySVSNujJvFuxWvIbnuIGULauxRfuIdxcGCNKXDqIAiDUIoTyTEkzsRQPrxkIaVoPibAeUsRpxSSEWvyZiDYmNvJmLSvEErwmOIaUwlTHHbUYYEbteraqHuYZlPjMmjupegPlrmbXYeAcuMzkwxKoGMVaAQhDlgUDtOLpERGtVgTvYsKKbbqMhELykTqsDnnnRZzCAxSmhcoBZaKjrcFpCtrlnekeZApVaOXodkXlVBlwczFJXnZWUmVtb3RlRnVuY3Rpb24=') then
                    table.insert(remoteList, obj:GetFullName())
                end
                findRemotes(obj)
            end
        end
        findRemotes(game)

        local resultStr = ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('aPJpDQkjOGLOEyRcVpyZLEYMYAiIeNDLrAmzfsOoMCkbIUupkuoJNAnlGaIxEkOYXkSTxtsZiBTnoGRXUWklNnrleAOPJrvFGeumSiMgLJlPcquvmkBhtHCGjVjTWzLLYTLEaAkjOgRzujiqZBbSDKYxqIWBLfJlrJAYwIBdotUdjKEsOqPINXgdxUFBUaXoNfNxAHHiTkySAuBzhXKIwAsYuvTtLZxSYkMvjGfezTqDugAnEFslhDImoOMKOwwhWXyvwefqqOyzFPdWcuQnlyMxcibYBUVbBueCkocGmNyMcUEaKVCHGKYpfMLEpNqITAmTyAUircuHaHmheGpRkyrbDUXhazyBsXlZqvFszOmTofeXErBHsLOMsVOUSouxPkUdJkpxRBWvfBeRlTEVMeQHZhlWzFRlnFoWRXwokAMHQwWBcwwhXvfPazLsUmVtb3RlIEV2ZW50IEFnZW50IHYxLjBcbkJ5IEBTcG9mdHlfMTIzXG5cbg==')
        for _, name in ipairs(remoteList) do
            resultStr = resultStr .. ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('IWWEvnURKBLxMbCgpxsVrTLtSZBvcenrxNQiXPAfaUEEnSReoPCbEfXbFmUZvAXPYUYaIXYBXbxFLpfqresCEDhpafmDuoYCfDmaojugYHOcruWuWOzBTjBNcZbeZDkiYwcuFxgNdkAqNSeRPQBAAXLEDkgBegPDmUCXZkwkNUwfJuFFPhgZYOZCUtxyYVRwMemoxNYCnHbjAphiUkTGbOFpFzCIADJkspsLpZJTyakLZLxockKTYoOOJOfeNQKUIJkLdLxIBiBYfMDsuBQpcGcbbUaepMArXYeIHCBEBaxcafeQQvxwYOuYhwxvGqeJrcqBUBxPxwMxlHUyfCMtptQKCNeGKUbHqJdTSVAuKqNtwaoMJBjANFTJOsWjjUHuOrzeygDJWApnUZUQdTnvTcKVuHXskwDfhjNjCkQEfQQLeYXeXtjubjGxIxkDLS0g') .. name .. ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('YuiUeQYyhmDXnFpMtkUwrHNdGBdvXlLcpUZUGfSowPOArNGIFDVjfzCrBBZaJAoAwiYSdeKNxiWrNAeiwhjPJjRkVzKssYEeYdGVjOqPFdLDeaRQUtCikBQeDfgMSwvofghjwbxHQeyaRVRnuvcmcdZEDbDgvQVLaxaWXqNFhMdXSBKwBFXnBnSPhVDpRMezfWHTWaAjCUwQrsgMHoIceWOEHOhtyUwlAPBPYAvQtpTZlxFDRzNMMXFlPwsAUSWvCsXgrDWjTxsAycmxmAuXPQnsfkIRYTjQIkTDeBLqwHlfmTtVDZFHjjEbeRbcyQaBtydXUcxYvSiDyvWoNLjUzdePFojuonVoFdmteYwuNpNJLddBdbPqUrylQmYyqPjZXyhOYhzDJeeYjNWKiTOPdlJXgtxsTxrpWzlMJHctOiWcfQmSxUIWbQlkAZKiXG4=')
        end

        pcall(function()
            setclipboard(resultStr)
        end)

        Rayfield:Notify({
            Title = ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('GMcIQMZlMCDktPoTrrFEokodstOoZGhKxtgjtEOVOwhSkIaUGvvmcZKEwwuyrWLcoRSYMeUIItjFLiHZbpqcKKcYBmehOwIXDDMbXjYMOdwDECbkLoGnwIHzUzAaMjOxkCXRSOHmhjwqKFIHnvfzHVUYDUlAemQxGJNtCvfKtuJzfyoPtnOLihQdLiMfldiWfMoFSHGiZwJFtRsvZBbEyBrsAZQHjbYjAYXvYGibWNahcFfUPGflNCQzeOcnzyelmJVdtpRONIYAoKIdKwTbtJPRKsZdjBFJuLSBTVGesSohuKBaNzNfxmSClAzsHhmKxserBKCopBcEPdexzoLROFUTyLvIRqAWCwrYbLPpajuUzgElkAhsOsSvzlKjDTSRawvJKLTzbbAeJVHSyzVSSxUTSMkwmfYHdRGprcEFyfBRSIpAduOImsqDcZklUmVtb3RlIEZpbmRlciAtIEFnZW50IC0gdjEuMA=='),
            Content = ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('woRYcRVclHLRmeTEYfAntEsjwKqKEPyBbdedSxxissIhOzWKoIInmXsLQPunbZSOFkzTxvtQbnhOoLEZQCGYnstxEbTYdRqxUnwCKnUDXkuVhEYOnvNxujnrcDHudQSfTNfreuKcozUOiQqeVtCyOojtkfQfEhsLSPSLJxjvZTrfKwlmVEfhGNowJQhRShpiYzYsPUKdSXuwSfksVZRIYPlxLLEehojqQoBuVUQvYnCBPCDfQKweKbQioMyOWDYvTSwwabwsJEwPWHbBooDtsVTXjHfXGquDoQRxifyDfRlVorqmVdbNCysQMtokekymbQPiKCfQCZShUSsGlejRFPPzsQYVkJZpSnQKViMRqgrbPllrJgEoqDEFEZoBXHTcjILjrYvNHxfoJPIEHCOOmlHdlaYuQcOICvscrBTdeQhPUwyHZEnIEQIBDHAyRm91bmQg') .. #remoteList .. ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('DlDjLEBomPXlwlaAaLfATIMBYnRMRCWxcTXqbSAgfjszUQyZjHzcPjFTZHKgvFZwJgioebXkStrPeDNPJzCFiKxeZoAAkJVbcWJGFimciOABXaArQxLIpMmTyXDVVUlHdCtabHOgzvliLESsFxZUbGRNGfcrJjRQiBkWaiGdfnhKiehZZIiKSMHoiUrJYOEruKRSYRrOarUmbDoFycOfSzTSQqlyqWifhrSFfTIHzUjDksGqeunTZvOSvUgqPrkbGuSBDPekzoprvTLoPsJFgQZFTTYkaYGQWTWTrFdGZiKRmOdadRfMvbvZNrCShvZENglAQGzEweLwlLknaxTmxoAgLcQzJWMwKFeNChLuuVjPZTFhxNlepXAKBvRtGhBcDoVAddCuOONKJRlAohSUrrQdqFrOCfwJzSUhLkGnzieXdgXSKkvGeHlCzaiZIFJlbW90ZUV2ZW50cy9SZW1vdGVGdW5jdGlvbnMuIENvcGllZCB0byBjbGlwYm9hcmQu'),
            Duration = 5,
            Image = 4483362458,
            Actions = {
                Ignore = {
                    Name = ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('trFLFmkhLYcDpdZWpUxEnaucqTZaAxFhYfuFjfEjYZuSKkGEwEyCaqnCVSRPjdnCTrotFNsFjBMLHCQBzCBULGMshNJtuQCTRpdAalhKzhEvguuXrouDQRMAyjjgzUPABYLBOLozVMAboZbvKdStlYMsivPVckoqboOqGHPEqoYsWxTIZlaiOuOZVkHuZTxytWYhLBsZBeVWqIkJAYnRAtyjrNNtqFiGfapwaSwPUepuAuLhQiHcxpxdxDLHuuLpgGPghyovfstNKoURRPFfWKRUdrEEPqkedputuupfgTlmwmgGNlgTLKzUkPAraWijINTtJfLCaqTrVEWseQICEzdchWbHZYmlXpkBqnVCofVUxotdouqFeuliSFwQYhBImCcNuouAYzIBdMWIYjxUdwTRxBuDCNEwDIHJkWdloBfDMjZAhGaWiksmBPlJT0s='),
                    Callback = function() end
                },
            },
        })
    end
})

local InfoTab = Window:CreateTab(ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('wImMLVqleZAzfTMJMVTInoNKLzzKNwTdtuIIsNzYYUtfuAhqcwyVGfOIDRXkHzqtwtCJGWVYYjSHaQqrCvXcwQRgjdzTtiatZGVrorJZNIhOMcMeMstOYuiAMYdyIFHBswBcdTAxkLuNnCqbjXvVFTwECDRjakpRHrbRIMLzCySLfcMCRzfcYDhmSKfCQuIMlfQAQtVxvfrwUAGzECBhVjzYfYomteEuxLFGnUMWJwXrkqComwSVRouxbMqUuJXqlZmiuKiIVOdgSmkagUDebDvkfrVAAlfdXjJpWhPRCnRbbxSksaOaXwCaJulBnZAYDhtWFxHwAbCDCJKuiTuOnoaiExtOMTbvdmLIRBtMDTGPDkCsRJXYdtOvKKtWdXtLLkxFkTGtlQSJDtcVgqrlbzekhGUNSZaqDrhkrGGbLKDOgghbKcsVvadESAMaSW5mbw=='))

InfoTab:CreateLabel(ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('sGZDCqYkMJiFzFoAIauzEtoDNWRsjYJozscInYTYpuikcGpCqRoBTlxgUSAnhjOsKIxuWnEPDfOihSXtXEaWgXFWJBYwdLKyjVpVzKSykViXbetJpQriaHXPsFWKCJXIYPuknRgnEKWJtYFrGwMPJZpgWorxAbjwMXGkhQfsFulixiTlPedwMzTysVeMMgdVpCaTmGodrRRmbaynpGVFfeKqsgtfymFsCZKJWECszHotXIAIOVYjjRpdPDSbfqPRdDGkbulNtlsYLmwVufGGFTOOTHiINODZqntMgeOZsekQUMfseLTYIMWoPNRQCjYaXUsARjdXUYGWGHButAhAKPlHpuqYDhlSfSldUCUaMWVIvUtTstkBjfVsDbUfpKkuafuUzBHTyDXLOskzdwLEUNRWdnNabRTWCgNKhQEDphGncFLFIuDwGTyrOatxVmVyc2lvbiBYLTUuMw=='))
InfoTab:CreateLabel(ZVAMbQDfYqSljCvJZbDoekjqAWvvYGcAhLHiSsafVCvGmcB('WUJtrVMvMiOvvYehNUsAGeuqfvEzUJPBSUmDmWHzqqUTOVcxJqhdaUIOJXuBcUaSeTwTvhSvbQdrKYlhduWGBDwarAttfiMGBwMSfZvUqprROdXGyXqKWqSYagzLzLSyPhxrjokqsTOGUlUSumjDTdaiNVWlhFdApaGPSZXhQiqufasxrwdArYFOLKKyAoCKDTbifzJTNdAzKXXdoahcNHLNwoAekQxvEcDCGeVUfzkYKGMWOwUaOHjDDrYNjUbQQZzIJskaJzfPgYpDovMOqKfnqHNzlUGSpnFsTOJfwPSaxCjpEQiZkRVfsSxmhiYMcPBpvbPavahZKIASctDmMGFgCtdxXjCXiIjZdvezoplseZAJBggKIIdOCHoDMyiRxlkLqSXOYpAAsxDtafVkRGYZeRhYLCdTbKpMbwKWjBEoKkPgaoOszrYNxDLWQ3JlYXRvciBAU3BvZnR5XzEyMw=='))

Rayfield:LoadConfiguration()   
